version: "3.9"

networks:
  sak-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: sak_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - sak-network

  app:
    build: .
    image: sak_redis_app
    container_name: sak_app
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - sak-network

volumes:
  redis-data:
